version: '3.8'
services:
  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://dt_user:dt_pass@db:5432/dt_db
      - SECRET_KEY=change_me
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: dt_user
      POSTGRES_PASSWORD: dt_pass
      POSTGRES_DB: dt_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
